<?php

return [
    [
        'title' => 'Casa Carlotta Lake Como - appartamento vista lago',
        'rooms' => 4,
        'beds' => 2,
        'square_meters' => 90,
        'bathrooms' => 1,
        'image' => 'uploads/casa-carlotta-lake-como.webp',
        'latitude' => 45.946527,
        'longitude' => 9.200882,
        'full_address' => 'Via Sossana, 2, 22025 Lezzeno CO, Italia',
    ],
    [
        'title' => 'Baita, Tana da l\'Ors, torna nella natura con un sorriso.',
        'rooms' => 3,
        'beds' => 3,
        'square_meters' => 30,
        'bathrooms' => 1,
        'image' => 'uploads/baia-tana-dal_ors-forgaria-nel-friuli.webp',
        'latitude' => 46.246388,
        'longitude' => 12.991657,
        'full_address' => 'Via Prat Centro 3, Forgaria Nel Friuli, Friuli-Venezia Giulia, Italia',
    ],
    [
        'title' => 'Elegante Attico in Centro con Vista - Park Privato',
        'rooms' => 3,
        'beds' => 2,
        'square_meters' => 90,
        'bathrooms' => 1,
        'image' => 'uploads/attico-in-centro-piazza-girolamo-genova.webp',
        'latitude' => 44.402204,
        'longitude' => 8.950645,
        'full_address' => 'Piazza Girolamo Savonarola 41, Genova, GE',
    ],
    [
        'title' => 'Amazing Rolli Apt Overlooking the Cathedral',
        'rooms' => 1,
        'beds' => 2,
        'square_meters' => 80,
        'bathrooms' => 2,
        'image' => 'uploads/amazing-rolli-apt-near-catedral-genova.webp',
        'latitude' => 44.407747,
        'longitude' => 8.930741,
        'full_address' => 'Via S. Lorenzo, 79, Genova, GE',
    ],
    [
        'title' => 'Casa Bruna',
        'rooms' => 1,
        'beds' => 1,
        'square_meters' => 60,
        'bathrooms' => 1,
        'image' => 'uploads/casa-bruna-genova.webp',
        'latitude' => 44.389685,
        'longitude' => 8.973846,
        'full_address' => 'Piazza Enrico Bassano, 8, 16146, Genova, GE',
    ],
    [
        'title' => '[Portofino] Villa Sori',
        'rooms' => 5,
        'beds' => 1,
        'square_meters' => 120,
        'bathrooms' => 1,
        'image' => 'uploads/villa-sori-portofino.webp',
        'latitude' => 44.365913,
        'longitude' => 9.120668,
        'full_address' => 'Via F. Crispi, 180, 16031 Sori GE',
    ],
    [
        'title' => 'Cubo, loft da rivista, a Genova',
        'rooms' => 5,
        'beds' => 1,
        'square_meters' => 90,
        'bathrooms' => 1,
        'image' => 'uploads/cubo-loft-genova.webp',
        'latitude' => 44.412018,
        'longitude' => 8.928235,
        'full_address' => 'Piazza S. Marcellino 6, 16124, Genova, GE',
    ],
    [
        'title' => 'Nel Cuore del Porto Antico a Genova',
        'rooms' => 3,
        'beds' => 2,
        'square_meters' => 100,
        'bathrooms' => 1,
        'image' => 'uploads/appartamento-porto-antico-genova.webp',
        'latitude' => 44.411832,
        'longitude' => 8.928763,
        'full_address' => 'Molo Ponte Calvi, 5, 16124 Genova GE',
    ],
    [
        'title' => 'Alcove sulla spiaggia di Boccadasse',
        'rooms' => 3,
        'beds' => 2,
        'square_meters' => 75,
        'bathrooms' => 1,
        'image' => 'uploads/alcove-boccadasse-genova.webp',
        'latitude' => 44.390114,
        'longitude' => 8.97423,
        'full_address' => 'Via Aurora, 3, 16146 Genova GE',
    ],
    [
        'title' => 'Exclusive Apt & Free Private Parking included!',
        'rooms' => 4,
        'beds' => 2,
        'square_meters' => 114,
        'bathrooms' => 1,
        'image' => 'uploads/exclusive-apt-genova.webp',
        'latitude' => 44.406132,
        'longitude' => 8.93357,
        'full_address' => '61 Via di Porta Soprana Genova, GE',
    ],
    [
        'title' => 'La Maison d epoque avec la vue sur Capri',
        'rooms' => 2,
        'beds' => 2,
        'square_meters' => 112,
        'bathrooms' => 2,
        'image' => 'uploads/la_maison_d_epoque_avec_la_vue_sur_capri.jpg',
        'latitude' => 40.609276,
        'longitude' => 14.357015,
        'full_address' => 'Via San Vito 9, 80061 Naples, Italy',
    ],
    [
        'title' => 'AnGiò holiday rooms',
        'rooms' => 2,
        'beds' => 3,
        'square_meters' => 93,
        'bathrooms' => 2,
        'image' => 'uploads/angiò_holiday_rooms.jpg',
        'latitude' => 40.839371,
        'longitude' => 14.254716,
        'full_address' => '84 Piazza Municipio, Port of Naples, 80133 Naples',
    ],
    [
        'title' => 'Parthenopes Nest',
        'rooms' => 3,
        'beds' => 4,
        'square_meters' => 89,
        'bathrooms' => 2,
        'image' => 'uploads/parthenopes_nest.jpg',
        'latitude' => 40.839371,
        'longitude' => 14.254716,
        'full_address' => 'Via Solitaria, 30, Chiaia, 80132 Naples',
    ],
    [
        'title' => 'Smile in Toledo',
        'rooms' => 2,
        'beds' => 2,
        'square_meters' => 98,
        'bathrooms' => 2,
        'image' => 'uploads/smile_in_toledo.jpg',
        'latitude' => 40.845668,
        'longitude' => 14.24929,
        'full_address' => '55 Via Toledo, 80134 Naples',
    ],
    [
        'title' => 'La Sirena a Mergellina',
        'rooms' => 2,
        'beds' => 2,
        'square_meters' => 88,
        'bathrooms' => 1,
        'image' => 'uploads/la_sirena_a_mergellina.jpg',
        'latitude' => 40.829462,
        'longitude' => 14.220199,
        'full_address' => 'Piazza Sannazaro 199 C - interno 3, Lungomare Caracciolo, 80122 Naples',
    ],
    [
        'title' => 'Vacation Home Agrumeto Flegreo',
        'rooms' => 3,
        'beds' => 5,
        'square_meters' => 110,
        'bathrooms' => 2,
        'image' => 'uploads/vacation_home_agrumeto_flegreo.jpg',
        'latitude' => 40.832587,
        'longitude' => 14.209897,
        'full_address' => 'via M. da Caravaggio,109, 80126 Naples,',
    ],
    [
        'title' => 'Casa di Lisa',
        'rooms' => 10,
        'beds' => 15,
        'square_meters' => 798,
        'bathrooms' => 10,
        'image' => 'uploads/casa_di_lisa.jpg',
        'latitude' => 40.861226,
        'longitude' => 14.254872,
        'full_address' => 'Salita della Riccia, 1, 4p, Capodimonte, 80137 Naples',
    ],
    [
        'title' => 'Villa Sofia e Sveva 2',
        'rooms' => 2,
        'beds' => 4,
        'square_meters' => 78,
        'bathrooms' => 1,
        'image' => 'uploads/villa_sofia_e_sveva_2.jpg',
        'latitude' => 40.860124,
        'longitude' => 14.250182,
        'full_address' => '61 Via San Severo a Capodimonte, Capodimonte, 80136 Naples',
    ],
    [
        'title' => 'Astrohouse 2.0',
        'rooms' => 1,
        'beds' => 2,
        'square_meters' => 75,
        'bathrooms' => 1,
        'image' => 'uploads/astrohouse_2.0.jpg',
        'latitude' => 40.851784,
        'longitude' => 14.263433,
        'full_address' => 'Vicoletto Zuroli, Naples Historical Centre, 80139 Naples',
    ],
    [
        'title' => 'Casa Macina',
        'rooms' => 2,
        'beds' => 4,
        'square_meters' => 89,
        'bathrooms' => 1,
        'image' => 'uploads/casa_macina.jpg',
        'latitude' => 40.841308,
        'longitude' => 14.24647,
        'full_address' => '28 Via Emanuele de Deo, Plebiscito, 80134 Naples',
    ],
    [
        'title' => 'Splendido appartamento con vista su San Marino sul mare di Rimini Miramare',
        'rooms' => 1,
        'beds' => 1,
        'square_meters' => 40,
        'bathrooms' => 1,
        'image' => 'uploads/miramare_vista_sul_mare.jpg',
        'latitude' => 44.031985,
        'longitude' => 12.620691,
        'full_address' => 'Viale Regina Margherita 261, 47924 Rimini',

    ],
    [
        'title' => 'Terrazza vicino al mare',
        'rooms' => 3,
        'beds' => 2,
        'square_meters' => 90,
        'bathrooms' => 1,
        'image' => 'uploads/terrazza_vicino_mare_miramare.jpg',
        'latitude' => 44.030544,
        'longitude' => 12.618372,
        'full_address' => 'Viale Ivo Oliveti 60, 47924 Rimini',

    ],
    [
        'title' => 'Platzlhof',
        'rooms' => 10,
        'beds' => 4,
        'square_meters' => 250,
        'bathrooms' => 3,
        'image' => 'uploads/platzlhof.jpg',
        'latitude' => 46.467729,
        'longitude' => 11.250869,
        'full_address' => 'Strada della Piazzetta 18, 39057 Appiano sulla Strada del Vino',

    ],
    [
        'title' => 'Schloss Freudenstein',
        'rooms' => 30,
        'beds' => 10,
        'square_meters' => 850,
        'bathrooms' => 6,
        'image' => 'uploads/schloss_bz.jpg',
        'latitude' => 46.459777,
        'longitude' => 11.244183,
        'full_address' => 'Strada Masaccio, 39057 Appiano sulla Strada del Vino',

    ],
    [
        'title' => 'Villa Schmid',
        'rooms' => 4,
        'beds' => 2,
        'square_meters' => 100,
        'bathrooms' => 2,
        'image' => 'uploads/schmid_bz.jpg',
        'latitude' => 46.508469,
        'longitude' => 11.345534,
        'full_address' => 'Via Fago 3, 39100 Bolzano',

    ],
    [
        'title' => 'Harmony Apt 3',
        'rooms' => 3,
        'beds' => 1,
        'square_meters' => 80,
        'bathrooms' => 1,
        'image' => 'uploads/harmony.jpg',
        'latitude' => 46.456545,
        'longitude' => 11.240563,
        'full_address' => 'Strada Masaccio 20, 39057 Appiano sulla Strada del Vino',

    ],
    [
        'title' => 'Il Falchetto',
        'rooms' => 3,
        'beds' => 1,
        'square_meters' => 60,
        'bathrooms' => 1,
        'image' => 'uploads/falchetto_bz.jpg',
        'latitude' => 46.44926,
        'longitude' => 11.16935,
        'full_address' => 'Località Regole, 38011 Sarnonico',

    ],
    [
        'title' => 'Manna Resort',
        'rooms' => 20,
        'beds' => 8,
        'square_meters' => 360,
        'bathrooms' => 4,
        'image' => 'uploads/manna.jpg',
        'latitude' => 46.330636,
        'longitude' => 11.303376,
        'full_address' => '39040 Montagna',

    ],
    [
        'title' => 'Thomaserhof',
        'rooms' => 10,
        'beds' => 4,
        'square_meters' => 160,
        'bathrooms' => 2,
        'image' => 'uploads/thomaserhof.jpg',
        'latitude' => 46.348721,
        'longitude' => 11.405653,
        'full_address' => 'Frazione Redagno di Sopra 6, 39040 Aldino',

    ],
    [
        'title' => 'Huanzhof Ferienwohnung Schwarzhorn',
        'rooms' => '12',
        'beds' => '6',
        'square_meters' => '200',
        'bathrooms' => '4',
        'image' => 'uploads/huanzhof.jpg',
        'latitude' => 46.365908,
        'longitude' => 11.390259,
        'full_address' => 'Lerch 34, 39040 Aldein',

    ],
    [
        'title' => 'Baciato dal sole',
        'rooms' => 3,
        'beds' => 5,
        'square_meters' => 120,
        'bathrooms' => 2,
        'image' => 'uploads/baciato_dal_sole.webp',
        'latitude' => 38.174974,
        'longitude' => 12.733683,
        'full_address' => 'Via Priamo 3, San Vito Lo Capo, Sicilia, Italia',
    ],
    [
        'title' => 'Ca.Sá Belló San Vito lo Capo',
        'rooms' => 2,
        'beds' => 4,
        'square_meters' => 90,
        'bathrooms' => 1,
        'image' => 'uploads/bello_san_vito_lo_capo.webp',
        'latitude' => 38.174959,
        'longitude' => 12.732961,
        'full_address' => 'Via Duca Degli Abruzzi 5, San Vito Lo Capo,Sicilia,Italia',
    ],
    [
        'title' => 'Suite Hermes, piscina e relax',
        'rooms' => 4,
        'beds' => 6,
        'square_meters' => 150,
        'bathrooms' => 3,
        'image' => 'uploads/suite_hermes.webp',
        'latitude' => 37.305598,
        'longitude' => 13.489236,
        'full_address' => 'Via Noci 3, Porto Empedocle, Sicilia, Italia',
    ],
    [
        'title' => 'Rapa Nui" b&b, un\'isola di pace',
        'rooms' => 5,
        'beds' => 8,
        'square_meters' => 160,
        'bathrooms' => 3,
        'image' => 'uploads/rapa_nui.webp',
        'latitude' => 37.305598,
        'longitude' => 12.467359,
        'full_address' => 'Via Noci 3, Porto Empedocle, Sicilia, Italia',
    ],
    [
        'title' => 'IL GIARDINO DI SICILIA',
        'rooms' => 8,
        'beds' => 16,
        'square_meters' => 180,
        'bathrooms' => 5,
        'image' => 'uploads/giardino_di_sicilia.jpg',
        'latitude' => 37.815376,
        'longitude' => 12.467359,
        'full_address' => 'Strada Cavadonna 12, Siracusa, Sicilia, Italia',
    ],
    [
        'title' => 'Camere Agriturismo Stallaini',
        'rooms' => 5,
        'beds' => 8,
        'square_meters' => 120,
        'bathrooms' => 4,
        'image' => 'uploads/agriturismo_stallaini.webp',
        'latitude' => 36.744502,
        'longitude' => 15.086139,
        'full_address' => 'Contrada Stallaini 3, 96017 Noto SR, Sicilia, Italia',
    ],
    [
        'title' => 'Camera matrimoniale con finestra vista mare',
        'rooms' => 4,
        'beds' => 6,
        'square_meters' => 150,
        'bathrooms' => 3,
        'image' => 'uploads/antonio_vivaldi.webp',
        'latitude' => 36.723341,
        'longitude' => 14.83527,
        'full_address' => 'Via Antonio Vivaldi 3, Pozzallo RG, Sicilia, Italia',
    ],
    [
        'title' => 'LIBECCIO · Boa Vista Favignana - Seminterrato "Libeccio"',
        'rooms' => 10,
        'beds' => 16,
        'square_meters' => 160,
        'bathrooms' => 4,
        'image' => 'uploads/boa_vista_favignana.webp',
        'latitude' => 37.919726,
        'longitude' => 12.323881,
        'full_address' => 'str. Costiera di Mezzogiorno 5, Favignana, Sicilia, Italia',
    ],
    [
        'title' => 'Casa vacanza Villa Giorgio di Francesca Rizzo',
        'rooms' => 7,
        'beds' => 12,
        'square_meters' => 160,
        'bathrooms' => 3,
        'image' => 'uploads/villa_giorgio.webp',
        'latitude' => 37.805248,
        'longitude' => 12.454625,
        'full_address' => 'Via Vita 5, Marsala, Sicilia, Italia',
    ],
    [
        'title' => 'Villa panoramica sull\'Etna con piscina vista mare',
        'rooms' => 2,
        'beds' => 3,
        'square_meters' => 80,
        'bathrooms' => 1,
        'image' => 'uploads/villa_panoramica_sull_etna.webp',
        'latitude' => 37.704768,
        'longitude' => 15.171399,
        'full_address' => 'Via Bellavista 18, 95014 Giarre CT, Sicilia, Italia',
    ],
    [
        'title' => 'Appartamento centrale a Cornaiano',
        'rooms' => 2,
        'beds' => 3,
        'square_meters' => 40,
        'bathrooms' => 2,
        'image' => 'uploads/appartamento_centrale_a_cornaiano.webp',
        'latitude' => 46.462855,
        'longitude' => 11.281142,
        'full_address' => 'Via S. Martino, 8, 39057 Bolzano BZ, Italia',
    ],
    [
        'title' => 'AL CAPANNO - portami in un posto carino',
        'rooms' => 1,
        'beds' => 1,
        'square_meters' => 65,
        'bathrooms' => 2,
        'image' => 'uploads/al_capanno.webp',
        'latitude' => 45.936505,
        'longitude' => 9.095019,
        'full_address' => 'Via Roma, 102, 22020 Schignano CO, Italia',
    ],
    [
        'title' => 'Villa-piscina calda(stagionale),sauna,bagno turco',
        'rooms' => 4,
        'beds' => 7,
        'square_meters' => 330,
        'bathrooms' => 5,
        'image' => 'uploads/villa-piscina_calda.webp',
        'latitude' => 45.903722,
        'longitude' => 9.29796,
        'full_address' => 'Via Privata Mons. G. Zunini, 16, 23865 Onno LC, Italia',
    ],
    [
        'title' => 'Chalet La Barona',
        'rooms' => 3,
        'beds' => 5,
        'square_meters' => 58,
        'bathrooms' => 2,
        'image' => 'uploads/chalet_la_barona.webp',
        'latitude' => 46.215031,
        'longitude' => 8.20489,
        'full_address' => 'Via Bugliaga, 17, 28868 Trasquera VB, Italia',
    ],
    [
        'title' => 'Attico di lusso sul mare con accesso privato al mare',
        'rooms' => 2,
        'beds' => 2,
        'square_meters' => 180,
        'bathrooms' => 2,
        'image' => 'uploads/attico_di_lusso_sul_mare_con_accesso_privato_al_mare.webp',
        'latitude' => 44.378488,
        'longitude' => 9.065026,
        'full_address' => 'Via Aurelia, 104, 16031 Bogliasco GE, Italia',
    ],
    [
        'title' => 'Casetta sul "Porto Antico" Piano primo',
        'rooms' => 1,
        'beds' => 2,
        'square_meters' => 84,
        'bathrooms' => 1,
        'image' => 'uploads/casetta_sul_porto_antico_piano_primo.webp',
        'latitude' => 40.952861,
        'longitude' => 17.303883,
        'full_address' => 'Via Porto, 15, 70043 Monopoli BA, Italia',
    ],
    [
        'title' => 'Casa Bianca di Federiciano 2',
        'rooms' => 1,
        'beds' => 1,
        'square_meters' => 35,
        'bathrooms' => 1,
        'image' => 'uploads/casa_bianca_di_federiciano_2.jpeg',
        'latitude' => 41.127108,
        'longitude' => 16.865002,
        'full_address' => 'Via S. Francesco D\'Assisi, 70122 Bari BA, Italia',
    ],
    [
        'title' => 'Villa Elena',
        'rooms' => 3,
        'beds' => 3,
        'square_meters' => 300,
        'bathrooms' => 3,
        'image' => 'uploads/villa_elena.jpg',
        'latitude' => 40.729027,
        'longitude' => 17.628496,
        'full_address' => 'Contrada Tamburroni, 72017 Ostuni, Italia',
    ],
    [
        'title' => 'G&P Luxury Villa | Piscina | Colazione',
        'rooms' => 2,
        'beds' => 2,
        'square_meters' => 145,
        'bathrooms' => '2',
        'image' => 'uploads/g&p_luxury_villa.webp',
        'latitude' => 44.546854,
        'longitude' => 11.458002,
        'full_address' => 'Via Roma 11,  40057 Granarolo dell\'Emilia, Italia',
    ],
    [
        'title' => 'Terratetto storico ristrutturato',
        'rooms' => 3,
        'beds' => 5,
        'square_meters' => 90,
        'bathrooms' => 2,
        'image' => 'uploads/terratetto_storico_ristrutturato.webp',
        'latitude' => 44.83669,
        'longitude' => 11.61385,
        'full_address' => 'Via Vegri 54,  44121 Ferrara, Italia',
    ],
    [
        'title' => 'Toscana | Agriturismo con piscina e ristorante',
        'rooms' => 2,
        'beds' => 4,
        'square_meters' => 280,
        'bathrooms' => 1,
        'image' => 'uploads/agriturismo_con_piscina.webp',
        'latitude' => 43.511056,
        'longitude' => 10.711471,
        'full_address' => 'Via Pieve de Pitti, 1, 56030 Terricciola PI, Italia',
    ],
    [
        'title' => 'Splendida Casa sull\'Albero a Pochi Minuti da Firenze',
        'rooms' => 1,
        'beds' => 3,
        'square_meters' => 35,
        'bathrooms' => 1,
        'image' => 'uploads/splendida_casa_sull_albero.webp',
        'latitude' => 43.732404,
        'longitude' => 11.214563,
        'full_address' => 'Via Volterrana, 50124 Firenze FI, Italia',
    ],
    [
        'title' => 'CasaMama',
        'rooms' => 1,
        'beds' => 2,
        'square_meters' => 130,
        'bathrooms' => 1,
        'image' => 'uploads/casamama.webp',
        'latitude' => 38.062287,
        'longitude' => 13.271886,
        'full_address' => 'Via Linea Ferrata, 90046 Monreale PA, Italia',
    ],
    [
        'title' => 'Appartamento-2 in antico casale a 4 km da Urbino',
        'rooms' => 1,
        'beds' => 2,
        'square_meters' => 160,
        'bathrooms' => 1,
        'image' => 'uploads/appartamento-2_in_antico_casale.webp',
        'latitude' => 43.702295,
        'longitude' => 12.653073,
        'full_address' => 'Via Ca\' le suore, 22, 61029 Urbino PU, Italia',
    ],
    [
        'title' => 'Fernanda 2: 2 camere, 5 persone, a 100m dalla spia',
        'rooms' => 2,
        'beds' => 4,
        'square_meters' => 100,
        'bathrooms' => 1,
        'image' => 'uploads/fernanda_2.webp',
        'latitude' => 44.171755,
        'longitude' => 9.608781,
        'full_address' => 'Via Ferrando, 3, 19015 Levanto SP, Italia',
    ],
    [
        'title' => 'New Apartment in Porta Nuova',
        'rooms' => 1,
        'beds' => 1,
        'square_meters' => 85,
        'bathrooms' => 1,
        'image' => 'uploads/new_apartment_in_porta_nuova.webp',
        'latitude' => 45.485847,
        'longitude' => 9.197776,
        'full_address' => 'Via Campanini, 4, 20124 Milano MI, Italia',
    ],
    [
        'title' => 'Il turchino nella city',
        'rooms' => 1,
        'beds' => 1,
        'square_meters' => 40,
        'bathrooms' => 1,
        'image' => 'uploads/il_turchino_nella_city.webp',
        'latitude' => 45.452303,
        'longitude' => 9.228688,
        'full_address' => 'Via del Turchino, 25, 20137 Milano MI, Italia',
    ],
    [
        'title' => 'Casa mia',
        'rooms' => 2,
        'beds' => 2,
        'square_meters' => 75,
        'bathrooms' => 1,
        'image' => 'uploads/casa_mia.webp',
        'latitude' => 45.426216,
        'longitude' => 9.608781,
        'full_address' => 'Via Jan Palach, 11, 20142 Milano MI, Italia',
    ],
    [
        'title' => 'Ripa',
        'rooms' => 1,
        'beds' => 2,
        'square_meters' => 90,
        'bathrooms' => 1,
        'image' => 'uploads/ripa.webp',
        'latitude' => 45.452115,
        'longitude' => 9.174747,
        'full_address' => 'vicolo privato lavandai, 4, 20144 Milano MI, Italia',
    ],
    [
        'title' => 'Corte Della Filanda',
        'rooms' => 1,
        'beds' => 1,
        'square_meters' => 40,
        'bathrooms' => 1,
        'image' => 'uploads/corte_della_filanda.webp',
        'latitude' => 44.171755,
        'longitude' => 9.608781,
        'full_address' => 'Via Verdi, 1, 20099 Sesto San Giovanni MI, Italia',
    ],
    [
        'title' => 'Attico nel Cuore di Milano',
        'rooms' => 1,
        'beds' => 2,
        'square_meters' => 55,
        'bathrooms' => 1,
        'image' => 'uploads/attico_nel_cuore_di_milano.webp',
        'latitude' => 45.477147,
        'longitude' => 9.181418,
        'full_address' => 'Via legnano, 32, 20124 Milano MI, Italia',
    ],
    [
        'title' => 'Prestigioso appartamento in zona Tortona',
        'rooms' => 2,
        'beds' => 3,
        'square_meters' => 100,
        'bathrooms' => 2,
        'image' => 'uploads/prestigioso_appartamento_in_via_tortona.webp',
        'latitude' => 45.453834,
        'longitude' => 9.157994,
        'full_address' => 'Via Andrea Solari, 50, 20144 Milano MI, Italia',
    ],
    [
        'title' => 'Loft Classico Zona Navigli',
        'rooms' => 1,
        'beds' => 2,
        'square_meters' => 110,
        'bathrooms' => 1,
        'image' => 'uploads/loft_classico_zona_navigli.webp',
        'latitude' => 45.433965,
        'longitude' => 9.191976,
        'full_address' => 'Via ferrari, 16, 20141 Milano MI, Italia',
    ],
    [
        'title' => 'Beatrice',
        'rooms' => 1,
        'beds' => 3,
        'square_meters' => 120,
        'bathrooms' => 1,
        'image' => 'uploads/beatrice.webp',
        'latitude' => 45.489981,
        'longitude' => 9.203593,
        'full_address' => 'Via Copernico, 30, 20125 Milano MI, Italia',
    ],
    [
        'title' => 'Un appartamento/monolocale, Busto Arsizio [Centro,con terrazza]',
        'rooms' => 1,
        'beds' => 2,
        'square_meters' => 80,
        'bathrooms' => 1,
        'image' => 'uploads/un_appartamento_monolocale_busto_arsizio_centro_con_terrazza.webp',
        'latitude' => 45.610887,
        'longitude' => 8.852483,
        'full_address' => 'Via cardinal tosi, 5, 20152 Busto Arsizio VA, Italia',
    ],
    [
        'title' => 'Corte Della Filanda',
        'rooms' => 1,
        'beds' => 1,
        'square_meters' => 40,
        'bathrooms' => 1,
        'image' => 'uploads/corte_della_filanda.webp',
        'latitude' => 44.171755,
        'longitude' => 9.608781,
        'full_address' => 'Via Verdi, 1, 20099 Sesto San Giovanni MI, Italia',
    ],
    [
        'title' => 'Apart Torino',
        'rooms' => 2,
        'beds' => 3,
        'square_meters' => 70,
        'bathrooms' => 1,
        'image' => 'uploads/apart_torino.jpg',
        'latitude' => 45.059171,
        'longitude' => 7.680751,
        'full_address' => 'Via Claudio Luigi Berthollet, 12, 10125 Torino TO, Italia',
    ],
    [
        'title' => 'Bright with stunning view apt.',
        'rooms' => 2,
        'beds' => 3,
        'square_meters' => 80,
        'bathrooms' => 1,
        'image' => 'uploads/stunning_view_torino.jpg',
        'latitude' => 45.071059,
        'longitude' => 7.697187,
        'full_address' => 'Via Sant Ottavio, 51 10124 Torino TO Italia',
    ],
    [
        'title' => 'Corte Realdi Luxury Rooms Torino',
        'rooms' => 2,
        'beds' => 3,
        'square_meters' => 90,
        'bathrooms' => 1,
        'image' => 'uploads/corte_realdi.jpg',
        'latitude' => 45.070128,
        'longitude' => 7.685562,
        'full_address' => 'P.za Castello, 67, 10121 Torino TO, Italia',
    ],
    [
        'title' => 'CasaCasalis - Immersi nella Torino Liberty',
        'rooms' => 3,
        'beds' => 5,
        'square_meters' => 120,
        'bathrooms' => 2,
        'image' => 'uploads/casa_salis.jpg',
        'latitude' => 45.080066,
        'longitude' => 7.658785,
        'full_address' => '4 Via Goffredo Casalis, 10143 Torino, Italia',
    ],
    [
        'title' => 'AHR Costa Serena Village',
        'rooms' => 3,
        'beds' => 5,
        'square_meters' => 120,
        'bathrooms' => 2,
        'image' => 'uploads/costa_serena.jpg',
        'latitude' => 41.196246,
        'longitude' => 9.340979,
        'full_address' => 'Loc Costa Serena Strada Per Porto Raphael, 07020 Palau, Italia',
    ],
    [
        'title' => 'Villa Minerva Palau',
        'rooms' => 4,
        'beds' => 8,
        'square_meters' => 180,
        'bathrooms' => 2,
        'image' => 'uploads/minerva_palau.jpg',
        'latitude' => 41.003802,
        'longitude' => 9.616757,
        'full_address' => 'Palau 07020 SS, Italia',
    ],
    [
        'title' => 'Is Molas Resort',
        'rooms' => 3,
        'beds' => 6,
        'square_meters' => 110,
        'bathrooms' => 2,
        'image' => 'uploads/is_molas.jpg',
        'latitude' => 39.008611,
        'longitude' => 9.002667,
        'full_address' => 'Pula 09010 CA, Italia',
    ],
    [
        'title' => 'Residence Porto Ulisse',
        'rooms' => 2,
        'beds' => 4,
        'square_meters' => 80,
        'bathrooms' => 1,
        'image' => 'uploads/porto_ulisse.jpg',
        'latitude' => 38.679621,
        'longitude' => 15.91373,
        'full_address' => 'Strada Cervo Sant Antonio, 89861 Parghelia, Italia',
    ],
    [
        'title' => 'Borgo di Santa Barbara',
        'rooms' => 4,
        'beds' => 6,
        'square_meters' => 120,
        'bathrooms' => 2,
        'image' => 'uploads/borgo_santa_barbara.jpg',
        'latitude' => 38.675458,
        'longitude' => 15.893095,
        'full_address' => 'Via Libertà 89861 Tropea VV, Italia',
    ],
    [
        'title' => 'Club San Diego',
        'rooms' => 3,
        'beds' => 4,
        'square_meters' => 90,
        'bathrooms' => 2,
        'image' => 'uploads/club_san_diego.jpg',
        'latitude' => 39.960135,
        'longitude' => 15.738157,
        'full_address' => 'Via Nazionale 59 or Via SS 18, 85046 Maratea, Italia',
    ],
    [
        'title' => 'Villa Susanna Degli Ulivi - Resort & Spa',
        'rooms' => 3,
        'beds' => 4,
        'square_meters' => 90,
        'bathrooms' => 2,
        'image' => 'uploads/susanna_degli_ulivi.jpg',
        'latitude' => 42.874246,
        'longitude' => 13.881687,
        'full_address' => 'Contrada Giardino, 64010 Colonnella, Italia',
    ],
    [
        'title' => 'Villa Novecento',
        'rooms' => 4,
        'beds' => 6,
        'square_meters' => 120,
        'bathrooms' => 2,
        'image' => 'uploads/villa_novecento.jpg',
        'latitude' => 45.795134,
        'longitude' => 6.969633,
        'full_address' => 'Viale Monte Bianco, 64, 11013 Courmayeur, Italia',
    ],
    [
        'title' => 'Apartment Europa',
        'rooms' => 3,
        'beds' => 4,
        'square_meters' => 80,
        'bathrooms' => 1,
        'image' => 'uploads/cervinia.jpg',
        'latitude' => 45.937727,
        'longitude' => 7.629525,
        'full_address' => 'Via C. Pellissier 2, 11021 Breuil-Cervinia, Italia',
    ],
    [
        'title' => 'Esclusivo attico con ampio terrazzo in Vaticano',
        'rooms' => 3,
        'beds' => 5,
        'square_meters' => 120,
        'bathrooms' => 2,
        'image' => 'uploads/attico_in_vaticano.webp',
        'latitude' => 41.90055,
        'longitude' => 12.444573,
        'full_address' => 'Via Aurelia, 208, 00165 Roma RM, Italia',
    ],
    [
        'title' => 'Tiber Nest Rome - Vista unica sullo skyline di Roma',
        'rooms' => 3,
        'beds' => 5,
        'square_meters' => 120,
        'bathrooms' => 2,
        'image' => 'uploads/skyline_roma.webp',
        'latitude' => 41.924785,
        'longitude' => 12.483677,
        'full_address' => 'Via Giovanni Antonelli, 51-41, 00197 Roma RM, Italia',
    ],
    [
        'title' => 'Villa Agrippina Gran Meliá',
        'rooms' => 6,
        'beds' => 8,
        'square_meters' => 220,
        'bathrooms' => 3,
        'image' => 'uploads/villa_agrippina.jpg',
        'latitude' => 41.899504,
        'longitude' => 12.459746,
        'full_address' => 'Via Urbano VIII, 16, 00165 Roma RM, Italia',
    ],
    [
        'title' => 'Love Suite Roma',
        'rooms' => 3,
        'beds' => 5,
        'square_meters' => 80,
        'bathrooms' => 1,
        'image' => 'uploads/suite_roma.jpg',
        'latitude' => 41.886806,
        'longitude' => 12.519364,
        'full_address' => 'Via la Spezia, 74, 00182 Roma RM, Italia',
    ],
    [
        'title' => 'Parkview Roma Suite',
        'rooms' => 2,
        'beds' => 4,
        'square_meters' => 60,
        'bathrooms' => 1,
        'image' => 'uploads/parkview_roma.jpg',
        'latitude' => 41.957899,
        'longitude' => 12.551043,
        'full_address' => 'Via Robert Musil, 00137 Roma, Italia',
    ],
    [
        'title' => 'Marco Simone Golf Ryder Cup View',
        'rooms' => 5,
        'beds' => 8,
        'square_meters' => 260,
        'bathrooms' => 3,
        'image' => 'uploads/marco_simone_golf.jpg',
        'latitude' => 41.974687,
        'longitude' => 12.631968,
        'full_address' => 'Via dell Auriga 16, 00012 Casale Sant Antonio, Italia',
    ],
    [
        'title' => 'Roman Oasis Villa',
        'rooms' => 3,
        'beds' => 5,
        'square_meters' => 90,
        'bathrooms' => 1,
        'image' => 'uploads/oasis_villa.jpg',
        'latitude' => 41.781493,
        'longitude' => 12.63081,
        'full_address' => '3 Vicolo del Sassone, 00043 Ciampino, Italia',
    ],
    [
        'title' => 'Villa Marilì',
        'rooms' => 2,
        'beds' => 4,
        'square_meters' => 80,
        'bathrooms' => 2,
        'image' => 'uploads/villa_marili.jpg',
        'latitude' => 42.087634,
        'longitude' => 12.191589,
        'full_address' => '1 Via Alcide de Gasperi, 00062 Bracciano, Italia',
    ],
    [
        'title' => 'Terrazza con vista su Piazza di Spagna',
        'rooms' => 1,
        'beds' => 1,
        'square_meters' => 80,
        'bathrooms' => 1,
        'image' => 'uploads/terrazza_vista_piazza_di_spagna.webp',
        'latitude' => 41.921709,
        'longitude' => 12.498291,
        'full_address' => 'Via Lovanio, 20 00198 Roma RM, Italia',
    ],
    [
        'title' => 'Luxury villa nel centro di Roma',
        'rooms' => 4,
        'beds' => 8,
        'square_meters' => 280,
        'bathrooms' => 3,
        'image' => 'uploads/luxury_villa_roma.webp',
        'latitude' => 41.9034,
        'longitude' => 12.480106,
        'full_address' => 'Via della Vite, 20-9 00187 Roma RM, Italia',
    ],
    [
        'title' => 'Roma Eur Luxury Villa',
        'rooms' => 6,
        'beds' => 10,
        'square_meters' => 300,
        'bathrooms' => 3,
        'image' => 'uploads/roma_eur.webp',
        'latitude' => 41.831304,
        'longitude' => 12.468103,
        'full_address' => 'Viale Europa, 175, 00144 Roma RM, Italia',
    ],
    [
        'title' => 'Fauno Urban Resort Roma',
        'rooms' => 6,
        'beds' => 10,
        'square_meters' => 200,
        'bathrooms' => 2,
        'image' => 'uploads/urban_resort.jpg',
        'latitude' => 41.88355,
        'longitude' => 12.486507,
        'full_address' => 'Via della Fonte di Fauno 31, Aventino, 00153 Roma, Italia',
    ],

];
