<?php

return [
    [
        'title' => 'Casa Carlotta Lake Como - appartamento vista lago',
        'rooms' => 4,
        'beds' => 2,
        'square_meters' => 90,
        'bathrooms' => 1,
        'image' => 'casa-carlotta-lake-como.webp',
        'latitude' => '45.946527',
        'longitude' => '9.200882',
        'full_address' => 'Via Sossana, 2, 22025 Lezzeno CO, Italia',
    ],
    [
        'title' => 'BaitaTana da l\'Ors, torna nella natura con un sorriso.',
        'rooms' => 3,
        'beds' => 3,
        'square_meters' => 30,
        'bathrooms' => 1,
        'image' => 'baia-tana-da-l\'ors-forgaria-nel-friuli.webp',
        'latitude' => '46.246388',
        'longitude' => '12.991657',
        'full_address' => 'Via Prat Centro 3, Forgaria Nel Friuli, Friuli-Venezia Giulia, Italia',
    ],
    [
        'title' => 'Elegante Attico in Centro con Vista - Park Privato',
        'rooms' => 3,
        'beds' => 2,
        'square_meters' => 90,
        'bathrooms' => 1,
        'image' => 'attico-in-centro-piazza-girolamo-genova.webp',
        'latitude' => '44.402204',
        'longitude' => '8.950645',
        'full_address' => 'Piazza Girolamo Savonarola 41, Genova, GE',
    ],
    [
        'title' => 'Amazing Rolli Apt Overlooking the Cathedral',
        'rooms' => 1,
        'beds' => 2,
        'square_meters' => 80,
        'bathrooms' => 2,
        'image' => 'amazing-rolli-apt-near-catedral-genova.webp',
        'latitude' => '44.407747',
        'longitude' => '8.930741',
        'full_address' => 'Via S. Lorenzo, 79, Genova, GE',
    ],
    [
        'title' => 'Casa Bruna',
        'rooms' => 1,
        'beds' => 1,
        'square_meters' => 60,
        'bathrooms' => 1,
        'image' => 'casa-bruna-genova.webp',
        'latitude' => '44.389685',
        'longitude' => '8.973846',
        'full_address' => 'Piazza Enrico Bassano, 8, 16146, Genova, GE',
    ],
    [
        'title' => '[Portofino] Villa Sori',
        'rooms' => 5,
        'beds' => 1,
        'square_meters' => 120,
        'bathrooms' => 1,
        'image' => 'villa-sori-portofino.webp',
        'latitude' => '44.365913',
        'longitude' => '9.120668',
        'full_address' => 'Via F. Crispi, 180, 16031 Sori GE',
    ],
    [
        'title' => 'Cubo, loft da rivista, a Genova',
        'rooms' => 5,
        'beds' => 1,
        'square_meters' => 90,
        'bathrooms' => 1,
        'image' => 'cubo-loft-genova.webp',
        'latitude' => '44.412018',
        'longitude' => '8.928235',
        'full_address' => 'Piazza S. Marcellino 6, 16124, Genova, GE',
    ],
    [
        'title' => 'Nel Cuore del Porto Antico a Genova',
        'rooms' => 3,
        'beds' => 2,
        'square_meters' => 100,
        'bathrooms' => 1,
        'image' => 'appartamento-porto-antico-genova.webp',
        'latitude' => '44.411832',
        'longitude' => '8.928763',
        'full_address' => 'Molo Ponte Calvi, 5, 16124 Genova GE',
    ],
    [
        'title' => 'Alcove sulla spiaggia di Boccadasse',
        'rooms' => 3,
        'beds' => 2,
        'square_meters' => 75,
        'bathrooms' => 1,
        'image' => 'alcove-boccadasse-genova.webp',
        'latitude' => '44.390114',
        'longitude' => '8.97423',
        'full_address' => 'Via Aurora, 3, 16146 Genova GE',
    ],
    [
        'title' => 'Exclusive Apt & Free Private Parking included!',
        'rooms' => 4,
        'beds' => 2,
        'square_meters' => 114,
        'bathrooms' => 1,
        'image' => 'exclusive-apt-genova.webp',
        'latitude' => '44.406132',
        'longitude' => '8.93357',
        'full_address' => '61 Via di Porta Soprana Genova, GE',
    ],
    [
        'title' => 'La Maison d epoque avec la vue sur Capri',
        'rooms' => 2,
        'beds' => 2,
        'square_meters' => 112,
        'bathrooms' => 2,
        'image' => 'La Maison d epoque avec la vue sur Capri',
        'latitude' => '40.609276',
        'longitude' => '14.357015',
        'full_address' => 'Via San Vito 9, 80061 Naples, Italy',
    ],
    [
        'title' => 'AnGiò holiday rooms',
        'rooms' => 2 ,
        'beds' => 3 ,
        'square_meters' => 93 ,
        'bathrooms' => 2 ,
        'image' => 'AnGiò holiday rooms',
        'latitude' => '40.839371',
        'longitude' => '14.254716',
        'full_address' => '84 Piazza Municipio, Port of Naples, 80133 Naples',
    ],
    [
        'title' => 'Parthenopes Nest',
        'rooms' => 3,
        'beds' => 4,
        'square_meters' => 89,
        'bathrooms' => 2,
        'image' => 'Parthenopes Nest',
        'latitude' => '40.839371',
        'longitude' => '14.254716',
        'full_address' => 'Via Solitaria, 30, Chiaia, 80132 Naples',
    ],
    [
        'title' => 'Smile in Toledo',
        'rooms' => 2,
        'beds' => 2,
        'square_meters' => 98,
        'bathrooms' => 2,
        'image' => 'Smile in Toledo',
        'latitude' => '40.845668',
        'longitude' => '14.24929',
        'full_address' => '55 Via Toledo, 80134 Naples',
    ],
    [
        'title' => 'La Sirena a Mergellina',
        'rooms' => 2,
        'beds' => 2,
        'square_meters' => 88,
        'bathrooms' => 1,
        'image' => 'La Sirena a Mergellina',
        'latitude' => '40.829462',
        'longitude' => '14.220199',
        'full_address' => 'Piazza Sannazaro 199 C - interno 3, Lungomare Caracciolo, 80122 Naples',
    ],
    [
        'title' => 'Vacation Home Agrumeto Flegreo',
        'rooms' => 3,
        'beds' => 5,
        'square_meters' => 110,
        'bathrooms' => 2,
        'image' => 'Vacation Home Agrumeto Flegreo',
        'latitude' => '40.832587',
        'longitude' => '14.209897',
        'full_address' => 'via M. da Caravaggio,109, 80126 Naples,',
    ],
    [
        'title' => 'Casa di Lisa',
        'rooms' => 10,
        'beds' => 15,
        'square_meters' => 798,
        'bathrooms' => 10,
        'image' => 'Casa di Lisa',
        'latitude' => '40.861226',
        'longitude' => '14.254872',
        'full_address' => 'Salita della Riccia, 1, 4p, Capodimonte, 80137 Naples',
    ],
    [
        'title' => 'Villa Sofia e Sveva 2',
        'rooms' => 2,
        'beds' => 4,
        'square_meters' => 78,
        'bathrooms' => 1,
        'image' => 'Villa Sofia e Sveva 2',
        'latitude' => '40.860124',
        'longitude' => '14.250182',
        'full_address' => '61 Via San Severo a Capodimonte, Capodimonte, 80136 Naples',
    ],
    [
        'title' => 'Astrohouse 2.0',
        'rooms' => 1,
        'beds' => 2,
        'square_meters' => 75,
        'bathrooms' => 1,
        'image' => 'Astrohouse 2.0',
        'latitude' => '40.851784',
        'longitude' => '14.263433',
        'full_address' => 'Vicoletto Zuroli, Naples Historical Centre, 80139 Naples',
    ],
    [
        'title' => 'Casa Macina',
        'rooms' => 2,
        'beds' => 4,
        'square_meters' => 89,
        'bathrooms' => 1,
        'image' => 'Casa Macina',
        'latitude' => '40.841308',
        'longitude' => '14.24647',
        'full_address' => '28 Via Emanuele de Deo, Plebiscito, 80134 Naples',
    ],

    [
        'title' => 'Splendido appartamento con vista su San Marino sul mare di Rimini Miramare',
        'rooms' => '1',
        'beds' => '1',
        'square_meters' => '40',
        'bathrooms' => '1',
        'image' => 'miramare_vista_sul_mare.jpg',
        'latitude' => '44.031985',
        'longitude' => '12.620691',
        'full_address' => 'Viale Regina Margherita 261, 47924 Rimini',
        
    ],
    [
        'title' => 'Terrazza vicino al mare',
        'rooms' => '3',
        'beds' => '2',
        'square_meters' => '90',
        'bathrooms' => '1',
        'image' => 'terrazza_vicino_mare_miramare.jpg',
        'latitude' => '44.030544',
        'longitude' => '12.618372',
        'full_address' => 'Viale Ivo Oliveti 60, 47924 Rimini',
        
    ],
    
    [
        'title' => 'Platzlhof',
        'rooms' => '10',
        'beds' => '4',
        'square_meters' => '250',
        'bathrooms' => '3',
        'image' => 'Platzlhof.jpg',
        'latitude' => '46.467729',
        'longitude' => '11.250869',
        'full_address' => 'Strada della Piazzetta 18, 39057 Appiano sulla Strada del Vino',
        
    ],

    [
        'title' => 'Schloss Freudenstein',
        'rooms' => '30',
        'beds' => '10',
        'square_meters' => '850',
        'bathrooms' => '6',
        'image' => 'schloss_bz.jpg',
        'latitude' => '46.459777',
        'longitude' => '11.244183',
        'full_address' => 'Strada Masaccio, 39057 Appiano sulla Strada del Vino',
        
    ],

    [
        'title' => 'Villa Schmid',
        'rooms' => '4',
        'beds' => '2',
        'square_meters' => '100',
        'bathrooms' => '2',
        'image' => 'schmid_bz.jpg',
        'latitude' => '46.508469',
        'longitude' => '11.345534',
        'full_address' => 'Via Fago 3, 39100 Bolzano',
        
    ],
    
    [
        'title' => 'Harmony Apt 3',
        'rooms' => '3',
        'beds' => '1',
        'square_meters' => '80',
        'bathrooms' => '1',
        'image' => 'harmony.jpg',
        'latitude' => '46.456545',
        'longitude' => '11.240563',
        'full_address' => 'Strada Masaccio 20, 39057 Appiano sulla Strada del Vino',
        
    ],

    [
        'title' => 'Il Falchetto',
        'rooms' => '3',
        'beds' => '1',
        'square_meters' => '60',
        'bathrooms' => '1',
        'image' => 'falchetto_bz.jpg',
        'latitude' => '46.44926',
        'longitude' => '11.16935',
        'full_address' => 'Località Regole, 38011 Sarnonico',
        
    ],

    [
        'title' => 'Manna Resort',
        'rooms' => '20',
        'beds' => '8',
        'square_meters' => '360',
        'bathrooms' => '4',
        'image' => 'Manna.jpg',
        'latitude' => '46.330636',
        'longitude' => '11.303376',
        'full_address' => '39040 Montagna',
        
    ],

    [
        'title' => 'Thomaserhof',
        'rooms' => '10',
        'beds' => '4',
        'square_meters' => '160',
        'bathrooms' => '2',
        'image' => 'thomaserhof.jpg',
        'latitude' => '46.348721',
        'longitude' => '11.405653',
        'full_address' => 'Frazione Redagno di Sopra 6, 39040 Aldino',
        
    ],

    [
        'title' => 'Huanzhof Ferienwohnung Schwarzhorn',
        'rooms' => '12',
        'beds' => '6',
        'square_meters' => '200',
        'bathrooms' => '4',
        'image' => 'huanzhof.jpg',
        'latitude' => '46.365908',
        'longitude' => '11.390259',
        'full_address' => 'Lerch 34, 39040 Aldein',
        
    ],
];
