<?php

return [
    [
        'title' => 'Casa Carlotta Lake Como - appartamento vista lago',
        'rooms' => 4,
        'beds' => 2,
        'square_meters' => 90,
        'bathrooms' => 1,
        'image' => 'casa-carlotta-lake-como.webp',
        'latitude' => '45.946527',
        'longitude' => '9.200882',
        'full_address' => 'Via Sossana, 2, 22025 Lezzeno CO, Italia',
    ],
    [
        'title' => 'BaitaTana da l\'Ors, torna nella natura con un sorriso.',
        'rooms' => 3,
        'beds' => 3,
        'square_meters' => 30,
        'bathrooms' => 1,
        'image' => 'baia-tana-da-l\'ors-forgaria-nel-friuli.webp',
        'latitude' => '46.246388',
        'longitude' => '12.991657',
        'full_address' => 'Via Prat Centro 3, Forgaria Nel Friuli, Friuli-Venezia Giulia, Italia',
    ],
    [
        'title' => 'Elegante Attico in Centro con Vista - Park Privato',
        'rooms' => 3,
        'beds' => 2,
        'square_meters' => 90,
        'bathrooms' => 1,
        'image' => 'attico-in-centro-piazza-girolamo-genova.webp',
        'latitude' => '44.402204',
        'longitude' => '8.950645',
        'full_address' => 'Piazza Girolamo Savonarola 41, Genova, GE',
    ],
    [
        'title' => 'Amazing Rolli Apt Overlooking the Cathedral',
        'rooms' => 1,
        'beds' => 2,
        'square_meters' => 80,
        'bathrooms' => 2,
        'image' => 'amazing-rolli-apt-near-catedral-genova.webp',
        'latitude' => '44.407747',
        'longitude' => '8.930741',
        'full_address' => 'Via S. Lorenzo, 79, Genova, GE',
    ],
    [
        'title' => 'Casa Bruna',
        'rooms' => 1,
        'beds' => 1,
        'square_meters' => 60,
        'bathrooms' => 1,
        'image' => 'casa-bruna-genova.webp',
        'latitude' => '44.389685',
        'longitude' => '8.973846',
        'full_address' => 'Piazza Enrico Bassano, 8, 16146, Genova, GE',
    ],
    [
        'title' => '[Portofino] Villa Sori',
        'rooms' => 5,
        'beds' => 1,
        'square_meters' => 120,
        'bathrooms' => 1,
        'image' => 'villa-sori-portofino.webp',
        'latitude' => '44.365913',
        'longitude' => '9.120668',
        'full_address' => 'Via F. Crispi, 180, 16031 Sori GE',
    ],
    [
        'title' => 'Cubo, loft da rivista, a Genova',
        'rooms' => 5,
        'beds' => 1,
        'square_meters' => 90,
        'bathrooms' => 1,
        'image' => 'cubo-loft-genova.webp',
        'latitude' => '44.412018',
        'longitude' => '8.928235',
        'full_address' => 'Piazza S. Marcellino 6, 16124, Genova, GE',
    ],
    [
        'title' => 'Nel Cuore del Porto Antico a Genova',
        'rooms' => 3,
        'beds' => 2,
        'square_meters' => 100,
        'bathrooms' => 1,
        'image' => 'appartamento-porto-antico-genova.webp',
        'latitude' => '44.411832',
        'longitude' => '8.928763',
        'full_address' => 'Molo Ponte Calvi, 5, 16124 Genova GE',
    ],
    [
        'title' => 'Alcove sulla spiaggia di Boccadasse',
        'rooms' => 3,
        'beds' => 2,
        'square_meters' => 75,
        'bathrooms' => 1,
        'image' => 'alcove-boccadasse-genova.webp',
        'latitude' => '44.390114',
        'longitude' => '8.97423',
        'full_address' => 'Via Aurora, 3, 16146 Genova GE',
    ],
    [
        'title' => 'Exclusive Apt & Free Private Parking included!',
        'rooms' => 4,
        'beds' => 2,
        'square_meters' => 114,
        'bathrooms' => 1,
        'image' => 'exclusive-apt-genova.webp',
        'latitude' => '44.406132',
        'longitude' => '8.93357',
        'full_address' => '61 Via di Porta Soprana Genova, GE',
    ],
];
